#!/bin/zsh

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
TMP="$SCRIPTPATH/tmp"

ENV=${ENV:=staging}

if [[ $ENV == "production" ]]
then
  echo "production environment can't be destroyed !"
  exit 0
fi

source $SCRIPTPATH/../config

source $SCRIPTPATH/lib

destroy_api_app

destroy_web_app
