#!/bin/zsh

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

ENV=${ENV:=staging}

if [[ $ENV == "production" ]]
then
  echo "production environment can't be destroyed !"
  exit 0
fi

source $SCRIPTPATH/../config

source $SCRIPTPATH/lib

detach_user_policy

clear_access_keys

delete_user

delete_policy

delete_bucket
